#!/usr/bin/ruby
# vi:ts=2:sw=2

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Find the sum of all the even-valued terms in the sequence which do not exceed
# four million.

fib = [0, 1]
i = 1
nextFib = fib[i]
sum = 0

while nextFib <= 4000000
	sum += nextFib if nextFib % 2 == 1
	nextFib = fib[0] + fib[1]
	fib[(i += 1) % 2] = nextFib
end

puts sum
